PRAGMA foreign_keys = ON;
CREATE TABLE legs (
id INTEGER PRIMARY KEY,
dep_IATA TEXT,
arr_IATA TEXT,
dep_datetime TEXT,
...
FOREIGN KEY(dep_IATA) REFERENCES locations(IATA) ON DELETE CASCADE,
FOREIGN KEY(arr_IATA) REFERENCES locations(IATA) ON DELETE CASCADE
);

  